### PR TITLE
JWS.txt

### PR DESCRIPTION
**Pull request by jadensschrock**
[JWS.txt](https://github.com/big-data-and-economics/big-data-class-materials/files/12623954/JWS.txt)

### CODE REVIEW

**Comment by kgcsport** [comment]
Hmm. You seem to have made a pull request (PR) to the generic repository for **big-data-and-economics** (the one I am using to maintain this class over the years) instead of the specific one for this semester (**ECON368-fall2023-big-data-and-economics/big-data-class-materials**). 

I'm not exactly sure how you did that, but I am impressed. 

On Tuesday, let's walk through the PR process to see if I can help figure out the issue.

**Comment by jadensschrock** [comment]
Whoops! Not sure how I did that either, but I’m glad you’re impressed. I
was just trying to turn in PS0. Chatting on Tuesday would be great. Hope
you stay dry this weekend!

Many thanks,
Jaden

**Comment by kgcsport** [comment]
Ah. Well you still have commit and push the PS0 repository with your answers.

**Comment by jadensschrock** [comment]
Darn I thought I did that… I’ll try again. Thank you!

**Comment by kgcsport** [comment]
Make sure you submit your PS0 repository (https://github.com/ECON368-fall2023-big-data-and-economics/ps0-jadensschrock)  tomorrow. 

1. You have to fill out the .Rmd and .tex files and knit and compile, respectively.
2. Commit these files
3. Push these files

**Pull request closed without merging**
